version: '3.8'

services:
  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "6379:6379"

  admin-app:
    build:
      context: ./admin-app
      dockerfile: Dockerfile
    container_name: admin-app
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  user-app:
    build:
      context: ./user-app
      dockerfile: Dockerfile
    container_name: user-app
    ports:
      - "3001:3001"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
